import unittest
import yaml

from bespokeasm.assembler.line_identifier import LineIdentifier
from bespokeasm.assembler.byte_code.assembled import AssembledInstruction
from bespokeasm.assembler.byte_code.parts import NumericByteCodePart

class TestBytecodeObjects(unittest.TestCase):

    def test_bytecode_assembly(self):
        test_line_id = LineIdentifier(42, 'test_bytecode_assembly')
        parts1 = [
            NumericByteCodePart(15, 4, True, 'big', test_line_id),
            NumericByteCodePart(3, 2, False, 'big', test_line_id),
            NumericByteCodePart(3, 2, False, 'big', test_line_id),
        ]

        ai1 = AssembledInstruction(123, parts1)
        self.assertEqual(ai1.byte_size, 1)
        self.assertEqual(ai1.get_bytes({}), bytearray([0xff]), 'generated bytes should match')

        parts2 = [
            NumericByteCodePart(8, 4, True, 'big', test_line_id),
            NumericByteCodePart(0x1122, 16, True, 'little', test_line_id),
            NumericByteCodePart(0x11223344, 32, True, 'little', test_line_id),
            NumericByteCodePart(0x8, 4, False, 'big', test_line_id),
        ]

        ai2 = AssembledInstruction(456, parts2)
        self.assertEqual(ai2.byte_size, 8)
        self.assertEqual(ai2.get_bytes({}), bytearray([0x80, 0x22, 0x11, 0x44, 0x33, 0x22, 0x11, 0x80]), 'generated bytes should match')